ALTER TABLE users ADD COLUMN email VARCHAR(255);
ALTER TABLE users ADD email VARCHAR(255);
ALTER TABLE users DROP COLUMN email;
ALTER TABLE users DROP email;
ALTER TABLE users MODIFY COLUMN email TEXT;
ALTER TABLE users MODIFY email TEXT;
ALTER TABLE users CHANGE COLUMN old_email new_email VARCHAR(255);
ALTER TABLE users CHANGE old_email new_email VARCHAR(255);
ALTER TABLE users RENAME TO customers;
ALTER TABLE users RENAME AS customers;
ALTER TABLE users RENAME customers;
ALTER TABLE users RENAME COLUMN old_name TO new_name;
ALTER TABLE users RENAME COLUMN old_name AS new_name;
ALTER TABLE users ADD INDEX idx_email (email);
ALTER TABLE users ADD KEY idx_email (email);
ALTER TABLE users DROP INDEX idx_email;
ALTER TABLE users DROP PRIMARY KEY;
ALTER TABLE users DROP FOREIGN KEY fk_user;
ALTER TABLE users DROP KEY fk_user;
ALTER TABLE users ADD CONSTRAINT pk_id PRIMARY KEY (id);
ALTER TABLE users DROP CONSTRAINT chk_age;
ALTER TABLE users DROP CHECK chk_age;
ALTER TABLE users ALGORITHM = INPLACE, ADD COLUMN email VARCHAR(255);
ALTER TABLE users ALGORITHM INPLACE, ADD COLUMN email VARCHAR(255);
ALTER TABLE users LOCK = NONE, ADD COLUMN email VARCHAR(255);
ALTER TABLE users LOCK NONE, ADD COLUMN email VARCHAR(255);
ALTER TABLE users ADD PARTITION (PARTITION p3 VALUES LESS THAN (2000));
ALTER TABLE users DROP PARTITION p0;
ALTER TABLE users ENGINE = InnoDB;
ALTER TABLE users ENGINE InnoDB;
ALTER TABLE t ADD COLUMN c INT;
ALTER TABLE users ADD COLUMN email VARCHAR(255) FIRST;
ALTER TABLE users ADD COLUMN email VARCHAR(255) AFTER name;
ALTER TABLE users ADD email VARCHAR(255) FIRST;
ALTER TABLE users ADD email VARCHAR(255) AFTER name;
ALTER TABLE users MODIFY COLUMN email TEXT FIRST;
ALTER TABLE users MODIFY COLUMN email TEXT AFTER name;
ALTER TABLE users MODIFY email TEXT FIRST;
ALTER TABLE users MODIFY email TEXT AFTER name;
ALTER TABLE users CHANGE COLUMN old_email new_email VARCHAR(255) FIRST;
ALTER TABLE users CHANGE COLUMN old_email new_email VARCHAR(255) AFTER name;
ALTER TABLE users CHANGE old_email new_email VARCHAR(255) FIRST;
ALTER TABLE users CHANGE old_email new_email VARCHAR(255) AFTER name;
ALTER TABLE users ADD INDEX idx_email (email) USING BTREE;
ALTER TABLE users ADD INDEX idx_email (email) USING HASH;
ALTER TABLE users ADD INDEX idx_email (email) KEY_BLOCK_SIZE = 8;
ALTER TABLE users ADD INDEX idx_email (email) KEY_BLOCK_SIZE 8;
ALTER TABLE users ADD INDEX idx_email (email) COMMENT 'Email index';
ALTER TABLE users ADD INDEX idx_email (email) COMMENT = 'Email index';
ALTER TABLE users ADD INDEX idx_email (email) VISIBLE;
ALTER TABLE users ADD INDEX idx_email (email) INVISIBLE;
ALTER TABLE users ADD INDEX idx_email (email) WITH PARSER ngram;
ALTER TABLE users ADD FULLTEXT INDEX ft_name (name);
ALTER TABLE users ADD FULLTEXT KEY ft_name (name);
ALTER TABLE users ADD SPATIAL INDEX sp_location (location);
ALTER TABLE users ADD SPATIAL KEY sp_location (location);
ALTER TABLE users DROP KEY idx_email;
ALTER TABLE users ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE users ADD FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE users ADD CONSTRAINT chk_age CHECK (age >= 0);
ALTER TABLE users ADD CHECK (age >= 0);
ALTER TABLE users ADD CONSTRAINT uk_email UNIQUE (email);
ALTER TABLE users ADD CONSTRAINT uk_email UNIQUE KEY (email);
ALTER TABLE users ADD CONSTRAINT uk_email UNIQUE INDEX (email);
ALTER TABLE users ADD UNIQUE (email);
ALTER TABLE users ADD UNIQUE KEY (email);
ALTER TABLE users ADD UNIQUE INDEX (email);
ALTER TABLE users ADD UNIQUE KEY uk_email (email);
ALTER TABLE users ADD UNIQUE INDEX uk_email (email);
ALTER TABLE users ADD PRIMARY KEY (id);
ALTER TABLE users DROP PARTITION p0, p1;
ALTER TABLE users ALGORITHM = DEFAULT;
ALTER TABLE users ALGORITHM = INSTANT;
ALTER TABLE users ALGORITHM = COPY;
ALTER TABLE users LOCK = DEFAULT;
ALTER TABLE users LOCK = SHARED;
ALTER TABLE users LOCK = EXCLUSIVE;
ALTER TABLE users CHARSET = utf8mb4;
ALTER TABLE users CHARSET utf8mb4;
ALTER TABLE users CHARACTER SET = utf8mb4;
ALTER TABLE users CHARACTER SET utf8mb4;
ALTER TABLE users DEFAULT CHARSET = utf8mb4;
ALTER TABLE users DEFAULT CHARACTER SET = utf8mb4;
ALTER TABLE users COLLATE = utf8mb4_unicode_ci;
ALTER TABLE users COLLATE utf8mb4_unicode_ci;
ALTER TABLE users DEFAULT COLLATE = utf8mb4_unicode_ci;
ALTER TABLE users AUTO_INCREMENT = 1000;
ALTER TABLE users AUTO_INCREMENT 1000;
ALTER TABLE users AVG_ROW_LENGTH = 100;
ALTER TABLE users KEY_BLOCK_SIZE = 8;
ALTER TABLE users MAX_ROWS = 1000000;
ALTER TABLE users MIN_ROWS = 10;
ALTER TABLE users STATS_SAMPLE_PAGES = 25;
ALTER TABLE users CHECKSUM = 1;
ALTER TABLE users DELAY_KEY_WRITE = 1;
ALTER TABLE users COMMENT = 'User table';
ALTER TABLE users COMMENT 'User table';
ALTER TABLE users CONNECTION = 'mysql://server';
ALTER TABLE users ENGINE_ATTRIBUTE = '{"key":"value"}';
ALTER TABLE users SECONDARY_ENGINE_ATTRIBUTE = '{"key":"value"}';
ALTER TABLE users DATA DIRECTORY = '/data/path';
ALTER TABLE users INDEX DIRECTORY = '/index/path';
ALTER TABLE users COMPRESSION = 'ZLIB';
ALTER TABLE users COMPRESSION = 'LZ4';
ALTER TABLE users COMPRESSION = 'NONE';
ALTER TABLE users ROW_FORMAT = DEFAULT;
ALTER TABLE users ROW_FORMAT = DYNAMIC;
ALTER TABLE users ROW_FORMAT = FIXED;
ALTER TABLE users ROW_FORMAT = COMPRESSED;
ALTER TABLE users ROW_FORMAT = REDUNDANT;
ALTER TABLE users ROW_FORMAT = COMPACT;
ALTER TABLE users WITH CHECK CHECK CONSTRAINT chk_age;
ALTER TABLE users NOCHECK CONSTRAINT chk_age;
ALTER TABLE users ANALYZE PARTITION p0, p1;
ALTER TABLE users CHECK PARTITION p0;
ALTER TABLE users COALESCE PARTITION 2;
ALTER TABLE users DISCARD PARTITION p0 TABLESPACE;
ALTER TABLE users IMPORT PARTITION p0 TABLESPACE;
ALTER TABLE users TRUNCATE PARTITION p0;
ALTER TABLE users DISCARD PARTITION p0, p1 TABLESPACE;
ALTER TABLE users IMPORT PARTITION p0, p1 TABLESPACE;
ALTER TABLE users ADD INDEX idx_email (email) COMMENT 'Email index';
ALTER TABLE users ADD INDEX idx_email (email) VISIBLE;
ALTER TABLE users ADD INDEX idx_email (email) INVISIBLE;
ALTER TABLE users ADD INDEX idx_email (email) WITH PARSER ngram;
ALTER TABLE users ADD INDEX idx_email (email) KEY_BLOCK_SIZE = 8;
ALTER TABLE users ADD SPATIAL INDEX sp_location (location);
ALTER TABLE users DROP PRIMARY KEY;
ALTER TABLE users DROP FOREIGN KEY fk_user;
ALTER TABLE users DROP KEY fk_user;
ALTER TABLE users DROP CHECK chk_age;
ALTER TABLE users ADD UNIQUE KEY uk_email (email);
ALTER TABLE users ADD UNIQUE INDEX uk_email (email);
ALTER TABLE users ADD FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE users ALGORITHM = DEFAULT;
ALTER TABLE users ALGORITHM = INSTANT;
ALTER TABLE users ALGORITHM = COPY;
ALTER TABLE users LOCK = DEFAULT;
ALTER TABLE users LOCK = SHARED;
ALTER TABLE users LOCK = EXCLUSIVE;
ALTER TABLE users CHARACTER SET = utf8mb4;
ALTER TABLE users CHARACTER SET utf8mb4;
ALTER TABLE users DEFAULT CHARSET = utf8mb4;
ALTER TABLE users DEFAULT CHARACTER SET = utf8mb4;
ALTER TABLE users COLLATE = utf8mb4_unicode_ci;
ALTER TABLE users COLLATE utf8mb4_unicode_ci;
ALTER TABLE users DEFAULT COLLATE = utf8mb4_unicode_ci;
ALTER TABLE users AVG_ROW_LENGTH = 100;
ALTER TABLE users KEY_BLOCK_SIZE = 8;
ALTER TABLE users MAX_ROWS = 1000000;
ALTER TABLE users MIN_ROWS = 10;
ALTER TABLE users STATS_SAMPLE_PAGES = 25;
ALTER TABLE users CHECKSUM = 1;
ALTER TABLE users DELAY_KEY_WRITE = 1;
ALTER TABLE users CONNECTION = 'mysql://server';
ALTER TABLE users ENGINE_ATTRIBUTE = '{"key":"value"}';
ALTER TABLE users SECONDARY_ENGINE_ATTRIBUTE = '{"key":"value"}';
ALTER TABLE users DATA DIRECTORY = '/data/path';
ALTER TABLE users INDEX DIRECTORY = '/index/path';
ALTER TABLE users COMPRESSION = 'ZLIB';
ALTER TABLE users COMPRESSION = 'LZ4';
ALTER TABLE users COMPRESSION = 'NONE';
ALTER TABLE users ROW_FORMAT = DEFAULT;
ALTER TABLE users ROW_FORMAT = FIXED;
ALTER TABLE users ROW_FORMAT = COMPRESSED;
ALTER TABLE users ROW_FORMAT = REDUNDANT;
ALTER TABLE users ROW_FORMAT = COMPACT;
ALTER TABLE users NOCHECK CONSTRAINT chk_age;
ALTER TABLE users CHECK PARTITION p0;
ALTER TABLE users RENAME AS customers;
ALTER TABLE users RENAME customers;
ALTER TABLE users RENAME COLUMN old_name AS new_name;
ALTER TABLE users ADD KEY idx_email (email);
ALTER TABLE users ADD FULLTEXT KEY ft_name (name);
ALTER TABLE users ADD SPATIAL KEY sp_location (location);
ALTER TABLE users ADD CONSTRAINT uk_email UNIQUE KEY (email);
ALTER TABLE users ADD CONSTRAINT uk_email UNIQUE INDEX (email);
ALTER TABLE users ADD UNIQUE KEY (email);
ALTER TABLE users ADD UNIQUE INDEX (email);
ALTER TABLE users DROP PARTITION p0, p1;
ALTER TABLE users ALGORITHM INPLACE;
ALTER TABLE users LOCK NONE;
ALTER TABLE users CHARSET utf8mb4;
ALTER TABLE users AUTO_INCREMENT 1000;
ALTER TABLE users COMMENT 'User table';
ALTER TABLE users ADD INDEX idx_email (email) USING HASH;
ALTER TABLE users ADD INDEX idx_email (email) KEY_BLOCK_SIZE 8;
ALTER TABLE users ADD INDEX idx_email (email) COMMENT = 'Email index';
ALTER TABLE users MODIFY COLUMN email TEXT FIRST;
ALTER TABLE users MODIFY COLUMN email TEXT AFTER name;
ALTER TABLE users MODIFY email TEXT FIRST;
ALTER TABLE users MODIFY email TEXT AFTER name;
ALTER TABLE users CHANGE COLUMN old_email new_email VARCHAR(255) FIRST;
ALTER TABLE users CHANGE COLUMN old_email new_email VARCHAR(255) AFTER name;
ALTER TABLE users CHANGE old_email new_email VARCHAR(255) FIRST;
ALTER TABLE users CHANGE old_email new_email VARCHAR(255) AFTER name;
ALTER TABLE users ADD CONSTRAINT chk_age CHECK (age >= 0);
ALTER TABLE users ADD email VARCHAR(255) FIRST;
ALTER TABLE users ADD email VARCHAR(255) AFTER name;
ALTER TABLE users DROP email;

ALTER TABLE users ADD COLUMN email VARCHAR(255) NOT NULL;
ALTER TABLE users ADD COLUMN email VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN email VARCHAR(255) DEFAULT 'test@example.com';
ALTER TABLE users ADD COLUMN id INT AUTO_INCREMENT;
ALTER TABLE users ADD COLUMN email VARCHAR(255) UNIQUE;
ALTER TABLE users ADD COLUMN email VARCHAR(255) UNIQUE KEY;
ALTER TABLE users ADD COLUMN id INT PRIMARY KEY;
ALTER TABLE users ADD COLUMN id INT KEY;
ALTER TABLE users ADD COLUMN email VARCHAR(255) COMMENT 'Email address';
ALTER TABLE users ADD COLUMN email VARCHAR(255) COLLATE utf8mb4_unicode_ci;
ALTER TABLE users ADD COLUMN email VARCHAR(255) CHARACTER SET utf8mb4;
ALTER TABLE users ADD COLUMN email VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE users ADD COLUMN status ENUM('active', 'inactive') DEFAULT 'active';
ALTER TABLE users ADD COLUMN price DECIMAL(10,2) UNSIGNED;
ALTER TABLE users ADD COLUMN age INT ZEROFILL;
ALTER TABLE users ADD COLUMN age INT UNSIGNED ZEROFILL;
ALTER TABLE users ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE users ADD COLUMN user_id INT REFERENCES users(id);
ALTER TABLE users MODIFY COLUMN email VARCHAR(255) NOT NULL;
ALTER TABLE users MODIFY COLUMN email VARCHAR(255) NULL;
ALTER TABLE users MODIFY COLUMN email VARCHAR(255) DEFAULT 'test@example.com';
ALTER TABLE users MODIFY COLUMN id INT AUTO_INCREMENT;
ALTER TABLE users MODIFY COLUMN email VARCHAR(255) UNIQUE;
ALTER TABLE users MODIFY COLUMN id INT PRIMARY KEY;
ALTER TABLE users MODIFY COLUMN email VARCHAR(255) COMMENT 'Email address';
ALTER TABLE users MODIFY COLUMN email VARCHAR(255) COLLATE utf8mb4_unicode_ci;
ALTER TABLE users MODIFY COLUMN email VARCHAR(255) CHARACTER SET utf8mb4;
ALTER TABLE users CHANGE COLUMN old_email new_email VARCHAR(255) NOT NULL;
ALTER TABLE users CHANGE COLUMN old_email new_email VARCHAR(255) NULL;
ALTER TABLE users CHANGE COLUMN old_email new_email VARCHAR(255) DEFAULT 'test@example.com';
ALTER TABLE users CHANGE COLUMN old_email new_email VARCHAR(255) COMMENT 'Email address';
ALTER TABLE users CHANGE COLUMN old_email new_email VARCHAR(255) COLLATE utf8mb4_unicode_ci;
ALTER TABLE users CHANGE COLUMN old_email new_email VARCHAR(255) CHARACTER SET utf8mb4;

ALTER TABLE users ADD COLUMN email VARCHAR(255) NOT NULL DEFAULT 'test@example.com' COMMENT 'Email' AFTER name;
ALTER TABLE users MODIFY COLUMN email VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'test@example.com' COMMENT 'Email' FIRST;
ALTER TABLE users ADD INDEX idx_complex (col1, col2, col3) USING BTREE COMMENT 'Complex index' VISIBLE;
ALTER TABLE users ADD CONSTRAINT fk_complex FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE users ADD COLUMN tags SET('tag1', 'tag2', 'tag3') DEFAULT 'tag1';
ALTER TABLE users MODIFY COLUMN price DECIMAL(10,2) UNSIGNED ZEROFILL NOT NULL DEFAULT 0.00;
ALTER TABLE users CHANGE COLUMN old_col new_col INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'ID column' FIRST;

alter table users add column email varchar(255);
ALTER TABLE users Add Column email Varchar(255);
alter table users drop column email;
ALTER TABLE users Drop Column email;
alter table users modify column email text;
ALTER TABLE users Modify Column email Text;
alter table users change column old_email new_email varchar(255);
ALTER TABLE users Change Column old_email new_email Varchar(255);
alter table users rename to customers;
ALTER TABLE users Rename To customers;
alter table users rename column old_name to new_name;
ALTER TABLE users Rename Column old_name To new_name;
alter table users add index idx_email (email);
ALTER TABLE users Add Index idx_email (email);
alter table users add key idx_email (email);
ALTER TABLE users Add Key idx_email (email);
alter table users add fulltext index ft_name (name);
ALTER TABLE users Add Fulltext Index ft_name (name);
alter table users add spatial index sp_location (location);
ALTER TABLE users Add Spatial Index sp_location (location);
alter table users drop index idx_email;
ALTER TABLE users Drop Index idx_email;
alter table users drop primary key;
ALTER TABLE users Drop Primary Key;
alter table users drop foreign key fk_user;
ALTER TABLE users Drop Foreign Key fk_user;
alter table users add constraint pk_id primary key (id);
ALTER TABLE users Add Constraint pk_id Primary Key (id);
alter table users add unique (email);
ALTER TABLE users Add Unique (email);
alter table users add check (age >= 0);
ALTER TABLE users Add Check (age >= 0);
alter table users drop constraint chk_age;
ALTER TABLE users Drop Constraint chk_age;
alter table users algorithm = default;
ALTER TABLE users Algorithm = Default;
alter table users algorithm = instant;
ALTER TABLE users Algorithm = Instant;
alter table users algorithm = inplace;
ALTER TABLE users Algorithm = Inplace;
alter table users algorithm = copy;
ALTER TABLE users Algorithm = Copy;
alter table users lock = default;
ALTER TABLE users Lock = Default;
alter table users lock = none;
ALTER TABLE users Lock = None;
alter table users lock = shared;
ALTER TABLE users Lock = Shared;
alter table users lock = exclusive;
ALTER TABLE users Lock = Exclusive;
alter table users row_format = default;
ALTER TABLE users Row_Format = Default;
alter table users row_format = dynamic;
ALTER TABLE users Row_Format = Dynamic;
alter table users row_format = fixed;
ALTER TABLE users Row_Format = Fixed;
alter table users row_format = compressed;
ALTER TABLE users Row_Format = Compressed;
alter table users row_format = redundant;
ALTER TABLE users Row_Format = Redundant;
alter table users row_format = compact;
ALTER TABLE users Row_Format = Compact;
alter table users add column email varchar(255) first;
ALTER TABLE users Add Column email Varchar(255) First;
alter table users add column email varchar(255) after name;
ALTER TABLE users Add Column email Varchar(255) After name;
alter table users add index idx_email (email) using btree;
ALTER TABLE users Add Index idx_email (email) Using Btree;
alter table users add index idx_email (email) using hash;
ALTER TABLE users Add Index idx_email (email) Using Hash;
alter table users add index idx_email (email) visible;
ALTER TABLE users Add Index idx_email (email) Visible;
alter table users add index idx_email (email) invisible;
ALTER TABLE users Add Index idx_email (email) Invisible;
alter table users add column email varchar(255) not null;
ALTER TABLE users Add Column email Varchar(255) Not Null;
alter table users add column email varchar(255) null;
ALTER TABLE users Add Column email Varchar(255) Null;
alter table users add column id int auto_increment;
ALTER TABLE users Add Column id Int Auto_Increment;
alter table users add column email varchar(255) unique;
ALTER TABLE users Add Column email Varchar(255) Unique;
alter table users add column id int primary key;
ALTER TABLE users Add Column id Int Primary Key;
alter table users add column price decimal(10,2) unsigned;
ALTER TABLE users Add Column price Decimal(10,2) Unsigned;
alter table users add column age int zerofill;
ALTER TABLE users Add Column age Int Zerofill;
alter table users add partition (partition p3 values less than (2000));
ALTER TABLE users Add Partition (Partition p3 Values Less Than (2000));
alter table users drop partition p0;
ALTER TABLE users Drop Partition p0;
alter table users analyze partition p0;
ALTER TABLE users Analyze Partition p0;
alter table users check partition p0;
ALTER TABLE users Check Partition p0;
alter table users truncate partition p0;
ALTER TABLE users Truncate Partition p0;
alter table users coalesce partition 2;
ALTER TABLE users Coalesce Partition 2;
