CALL my_procedure();
CALL my_procedure(1, 'test');
CALL mydb.my_procedure();
CALL my_procedure(@out_param);
CALL proc_name;
CALL schema.proc_name;
CALL my_proc(NULL);
CALL my_proc(TRUE, FALSE);
CALL my_proc(123, -456, 3.14);
CALL my_proc('string', "double");
CALL my_proc(DATE '2023-01-01', TIME '12:30:00', TIMESTAMP '2023-01-01 12:30:00');
CALL my_proc(@var1, @var2, @@session_var);
CALL my_proc(:param1, :param2);
CALL my_proc(col_name, table.col_name, db.table.col_name);
CALL my_proc(func());
CALL my_proc(func(arg1, arg2));
CALL my_proc(nested_func(inner_func()));
CALL my_proc((1 + 2), (3 * 4));
CALL my_proc((1 + 2 * 3), (4 - 5 / 6));
CALL my_proc(1, 'test', NULL, TRUE, @var, :param, col, func(), (1+2));
CALL `quoted_proc`();
CALL `schema`.`proc`();
