DELETE FROM users WHERE id = 1;
DELETE t1, t2 FROM users t1 JOIN orders t2 ON t1.id = t2.user_id WHERE t1.id = 1;
DELETE FROM users AS u WHERE u.id = 1;
WITH cte AS (SELECT id FROM temp) DELETE FROM users WHERE id IN (SELECT id FROM cte);
DELETE FROM users;
DELETE t1, t2 FROM t1 INNER JOIN t2 WHERE t1.id = t2.id;
DELETE FROM users u JOIN orders o ON u.id = o.user_id WHERE u.id = 1;
DELETE FROM users WHERE NOT active;
DELETE FROM users WHERE ISNULL(deleted_at);
DELETE FROM users ORDER BY id DESC;
DELETE FROM users LIMIT 10;
DELETE t1 FROM users t1 JOIN orders t2 ON t1.id = t2.user_id;
DELETE t1 FROM t1, DUAL WHERE t1.id = 1;
DELETE users FROM users JOIN orders ON users.id = orders.user_id WHERE orders.status = "cancelled";
DELETE FROM users WHERE created_at < DATE_SUB(NOW(), INTERVAL 1 YEAR);
DELETE FROM users WHERE id IN (SELECT user_id FROM banned_users);
DELETE FROM users WHERE age < 18 OR status = 'inactive';
DELETE FROM users ORDER BY created_at ASC LIMIT 5;
DELETE FROM users WHERE id = 1 ORDER BY id LIMIT 1;
DELETE t1, t2, t3 FROM t1 JOIN t2 ON t1.id = t2.id JOIN t3 ON t2.id = t3.id WHERE t1.status = 'deleted';
DELETE FROM users LEFT JOIN orders ON users.id = orders.user_id WHERE orders.id IS NULL;
DELETE FROM users RIGHT JOIN orders ON users.id = orders.user_id WHERE users.id IS NULL;
DELETE FROM users CROSS JOIN orders WHERE users.id = orders.user_id;
DELETE t1 FROM t1 LEFT JOIN t2 ON t1.id = t2.id WHERE t2.id IS NULL;
DELETE t1 FROM t1 RIGHT JOIN t2 ON t1.id = t2.id WHERE t1.id IS NULL;
DELETE t1 FROM t1 CROSS JOIN t2 WHERE t1.id = t2.id;
DELETE FROM db1.users WHERE id = 1;
DELETE FROM `database`.`table` WHERE id = 1;
DELETE t1, t2 FROM db1.t1 JOIN db2.t2 ON t1.id = t2.id;
WITH RECURSIVE cte AS (SELECT 1 AS n UNION ALL SELECT n+1 FROM cte WHERE n < 5) DELETE FROM users WHERE id IN (SELECT n FROM cte);
DELETE FROM users WHERE id BETWEEN 1 AND 100;
DELETE FROM users WHERE name LIKE 'test%';
DELETE FROM users WHERE email REGEXP '^test';
DELETE FROM users WHERE status IN ('inactive', 'deleted');
DELETE FROM users WHERE created_at IS NULL;
DELETE FROM users WHERE created_at IS NOT NULL;
DELETE FROM users WHERE id > 100 AND status = 'inactive';
DELETE FROM users WHERE id = 1 OR id = 2;
DELETE FROM users WHERE (id = 1 OR id = 2) AND status = 'active';
DELETE FROM users WHERE id = (SELECT MAX(id) FROM temp);
DELETE t1 FROM t1, t2 WHERE t1.id = t2.id;
DELETE t1, t2 FROM t1, t2 WHERE t1.id = t2.id;
DELETE FROM users WHERE EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id);
DELETE FROM users WHERE NOT EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id);
DELETE FROM users WHERE id = ANY (SELECT user_id FROM banned);
DELETE FROM users WHERE MATCH(name, description) AGAINST ('test' IN BOOLEAN MODE);
DELETE FROM users ORDER BY id ASC;
DELETE FROM users ORDER BY created_at DESC, id ASC;
DELETE FROM users LIMIT 100;
DELETE FROM users ORDER BY id LIMIT 50;
DELETE FROM users WHERE id > 0 ORDER BY id DESC LIMIT 10;
WITH cte1 AS (SELECT id FROM t1), cte2 AS (SELECT id FROM t2) DELETE FROM users WHERE id IN (SELECT id FROM cte1) OR id IN (SELECT id FROM cte2);
DELETE t1 FROM t1 STRAIGHT_JOIN t2 ON t1.id = t2.id;
DELETE FROM users WHERE id = 1 + 2;
DELETE FROM users WHERE price * quantity > 1000;
DELETE FROM users WHERE status = CONCAT('in', 'active');
DELETE FROM users WHERE created_at < NOW();
DELETE FROM users WHERE YEAR(created_at) = 2020;
DELETE FROM users WHERE CAST(id AS CHAR) = '123';
DELETE FROM users WHERE CASE WHEN status = 'active' THEN 1 ELSE 0 END = 0;
DELETE FROM users WHERE id IN (1, 2, 3, 4, 5);
DELETE FROM users WHERE (id, status) IN ((1, 'active'), (2, 'inactive'));
DELETE FROM users WHERE id = @user_id;
DELETE FROM users WHERE id = :param;
DELETE FROM users WHERE id = ?;
DELETE t1 FROM (SELECT * FROM users WHERE status = 'inactive') t1;
DELETE FROM users WHERE id IN (SELECT id FROM (SELECT id FROM temp) AS subq);
DELETE t1, t2 FROM t1 INNER JOIN t2 USING (id);
DELETE t1 FROM t1 LEFT JOIN t2 USING (id) WHERE t2.id IS NULL;
DELETE FROM users WHERE name COLLATE utf8mb4_bin = 'test';
DELETE FROM users WHERE id & 1 = 1;
DELETE FROM users WHERE id | 2 = 3;
DELETE FROM users WHERE id ^ 1 = 0;
DELETE FROM users WHERE id << 1 = 4;
DELETE FROM users WHERE id >> 1 = 1;
DELETE FROM users WHERE ~id = -2;
DELETE FROM users WHERE id DIV 2 = 5;
DELETE FROM users WHERE id MOD 2 = 0;
DELETE FROM users WHERE id % 2 = 1;
DELETE FROM users WHERE -id = -1;
DELETE FROM users WHERE +id = 1;
DELETE FROM users WHERE !active;
DELETE FROM users WHERE id XOR status;
DELETE FROM users WHERE id && status;
DELETE FROM users WHERE name || surname = 'JohnDoe';
DELETE FROM users WHERE JSON_EXTRACT(data, '$.active') = false;
DELETE FROM users WHERE data->'$.status' = 'inactive';
DELETE FROM users WHERE data->>'$.name' = 'test';
DELETE FROM users WHERE INTERVAL 1 DAY + created_at < NOW();
DELETE FROM users WHERE EXTRACT(YEAR FROM created_at) = 2020;
DELETE FROM users WHERE TRIM(BOTH ' ' FROM name) = 'test';
DELETE FROM users WHERE CONVERT(id, CHAR) = '123';
DELETE FROM users WHERE id = CURRENT_USER();
DELETE FROM users WHERE created_at = CURRENT_DATE;
DELETE FROM users WHERE created_at = CURRENT_TIME;
DELETE FROM users WHERE created_at = CURRENT_TIMESTAMP;
DELETE FROM users WHERE created_at = CURRENT_TIMESTAMP();
DELETE FROM users WHERE id = LAST_INSERT_ID();
DELETE FROM users WHERE name = DATABASE();
DELETE FROM users WHERE id = CONNECTION_ID();
DELETE FROM users WHERE CHAR_LENGTH(name) > 10;
DELETE FROM users WHERE LENGTH(name) > 10;
DELETE FROM users WHERE UPPER(name) = 'TEST';
DELETE FROM users WHERE LOWER(name) = 'test';
DELETE FROM users WHERE SUBSTRING(name, 1, 4) = 'test';
DELETE FROM users WHERE CONCAT(first_name, ' ', last_name) = 'John Doe';
DELETE FROM users WHERE COALESCE(email, 'none') = 'none';
DELETE FROM users WHERE IFNULL(status, 'active') = 'active';
DELETE FROM users WHERE NULLIF(status, 'active') IS NULL;
DELETE FROM users WHERE IF(active, 1, 0) = 0;
DELETE FROM users WHERE GREATEST(id, 100) = 100;
DELETE FROM users WHERE LEAST(id, 100) = id;
DELETE FROM users WHERE ABS(balance) > 1000;
DELETE FROM users WHERE CEIL(price) = 100;
DELETE FROM users WHERE FLOOR(price) = 99;
DELETE FROM users WHERE ROUND(price, 2) = 99.99;
DELETE FROM users WHERE SQRT(id) < 10;
DELETE FROM users WHERE POW(id, 2) = 100;
DELETE FROM users WHERE MOD(id, 2) = 0;
DELETE FROM users WHERE RAND() < 0.5;
DELETE FROM users WHERE DATE(created_at) = '2020-01-01';
DELETE FROM users WHERE TIME(created_at) = '12:00:00';
DELETE FROM users WHERE TIMESTAMP(created_at) = '2020-01-01 12:00:00';
DELETE FROM users WHERE YEAR(created_at) = 2020;
DELETE FROM users WHERE MONTH(created_at) = 1;
DELETE FROM users WHERE DAY(created_at) = 1;
DELETE FROM users WHERE HOUR(created_at) = 12;
DELETE FROM users WHERE MINUTE(created_at) = 30;
DELETE FROM users WHERE SECOND(created_at) = 45;
DELETE FROM users WHERE DAYOFWEEK(created_at) = 1;
DELETE FROM users WHERE DAYOFMONTH(created_at) = 15;
DELETE FROM users WHERE DAYOFYEAR(created_at) = 100;
DELETE FROM users WHERE WEEK(created_at) = 10;
DELETE FROM users WHERE WEEKDAY(created_at) = 0;
DELETE FROM users WHERE QUARTER(created_at) = 2;
DELETE FROM users WHERE DATE_ADD(created_at, INTERVAL 1 DAY) < NOW();
DELETE FROM users WHERE DATE_SUB(created_at, INTERVAL 1 MONTH) < NOW();
DELETE FROM users WHERE ADDDATE(created_at, 7) < NOW();
DELETE FROM users WHERE SUBDATE(created_at, 7) < NOW();
DELETE FROM users WHERE DATEDIFF(NOW(), created_at) > 365;
DELETE FROM users WHERE TIMESTAMPDIFF(DAY, created_at, NOW()) > 30;
DELETE FROM users WHERE TIMESTAMPADD(MONTH, 1, created_at) < NOW();
DELETE FROM users WHERE DATE_FORMAT(created_at, '%Y-%m-%d') = '2020-01-01';
DELETE FROM users WHERE STR_TO_DATE('2020-01-01', '%Y-%m-%d') = created_at;
DELETE FROM users WHERE UNIX_TIMESTAMP(created_at) < 1577836800;
DELETE FROM users WHERE FROM_UNIXTIME(1577836800) = created_at;
