DROP TRIGGER my_trigger;
DROP TRIGGER IF EXISTS my_trigger;
DROP TRIGGER mydb.my_trigger;
DROP TABLE users;
DROP TABLE IF EXISTS users;
DROP TABLE users, orders;
DROP TABLE IF EXISTS users, orders;
DROP TABLE mydb.users;
DROP TABLE IF EXISTS mydb.users, mydb.orders;
DROP DATABASE mydb;
DROP DATABASE IF EXISTS mydb;
DROP SCHEMA myschema;
DROP SCHEMA IF EXISTS myschema;
DROP VIEW myview;
DROP VIEW IF EXISTS myview;
DROP VIEW myview, otherview;
DROP VIEW IF EXISTS myview, otherview;
DROP VIEW myview RESTRICT;
DROP VIEW myview CASCADE;
DROP VIEW IF EXISTS myview RESTRICT;
DROP VIEW IF EXISTS myview CASCADE;
DROP VIEW mydb.myview;
DROP VIEW IF EXISTS mydb.myview, mydb.otherview CASCADE;
DROP INDEX idx_name ON users;
DROP INDEX idx_name ON mydb.users;
DROP INDEX idx_name ON users ALGORITHM = DEFAULT;
DROP INDEX idx_name ON users ALGORITHM = INSTANT;
DROP INDEX idx_name ON users ALGORITHM = INPLACE;
DROP INDEX idx_name ON users ALGORITHM = COPY;
DROP INDEX idx_name ON users LOCK = DEFAULT;
DROP INDEX idx_name ON users LOCK = NONE;
DROP INDEX idx_name ON users LOCK = SHARED;
DROP INDEX idx_name ON users LOCK = EXCLUSIVE;
DROP INDEX idx_name ON users ALGORITHM = INPLACE LOCK = NONE;
DROP INDEX idx_name ON users LOCK = SHARED ALGORITHM = COPY;
DROP TRIGGER IF EXISTS mydb.my_trigger;
