GRANT SELECT ON mydb.* TO user1;
GRANT SELECT, INSERT ON mydb.* TO user1;
GRANT SELECT ON mydb.* TO user1@localhost;
GRANT SELECT ON mydb.* TO user1 WITH GRANT OPTION;
GRANT SELECT (id, name) ON mydb.users TO user1;
GRANT SELECT ON TABLE mydb.users TO user1;
GRANT SELECT ON mydb.users TO 'user1'@'localhost', 'user2'@'%';
GRANT ALL ON mydb.* TO user1;
GRANT EXECUTE ON PROCEDURE mydb.myproc TO user1;
GRANT EXECUTE ON FUNCTION mydb.myfunc TO user1;
GRANT PROXY ON 'user1'@'localhost' TO 'user2'@'localhost';
GRANT role1 TO user1;
GRANT role1, role2 TO user1, user2;
GRANT SELECT ON *.* TO user1;
GRANT ALTER ON mydb.* TO user1;
GRANT CREATE VIEW ON mydb.* TO user1;
GRANT CREATE ON mydb.* TO user1;
GRANT DELETE ON mydb.* TO user1;
GRANT DROP ON mydb.* TO user1;
GRANT GRANT OPTION ON mydb.* TO user1;
GRANT INDEX ON mydb.* TO user1;
GRANT INSERT ON mydb.* TO user1;
GRANT REFERENCES ON mydb.* TO user1;
GRANT SHOW VIEW ON mydb.* TO user1;
GRANT TRIGGER ON mydb.* TO user1;
GRANT UPDATE ON mydb.* TO user1;
GRANT SELECT, INSERT, UPDATE, DELETE ON mydb.users TO user1;
GRANT ALL ON TABLE mydb.users TO user1;
GRANT SELECT (col1), INSERT (col2, col3) ON mydb.users TO user1;
GRANT SELECT ON * TO user1;
GRANT SELECT ON mydb.users TO user1@localhost WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION mydb.func TO user1 WITH GRANT OPTION;
GRANT PROXY ON 'user1'@'localhost' TO 'user2'@'localhost' WITH ADMIN OPTION;
GRANT role1 TO user1 WITH ADMIN OPTION;
GRANT role1, role2 TO user1@localhost, user2@localhost WITH ADMIN OPTION;
GRANT ALL ON FUNCTION mydb.func TO user1;
GRANT ALL ON PROCEDURE mydb.proc TO user1;
GRANT SELECT, INSERT, UPDATE ON TABLE mydb.* TO user1;
GRANT CREATE VIEW, SHOW VIEW ON mydb.* TO user1;
GRANT ALTER, DROP, CREATE ON mydb.* TO user1;
GRANT INDEX, REFERENCES ON mydb.users TO user1;
GRANT TRIGGER, DELETE ON mydb.users TO user1;
GRANT UPDATE (col1, col2), SELECT (col3) ON mydb.users TO user1;
GRANT GRANT OPTION ON TABLE mydb.users TO user1;
GRANT EXECUTE ON PROCEDURE mydb.proc TO user1 WITH GRANT OPTION;
