SELECT id, ROW_NUMBER() OVER w FROM t WINDOW w AS (ORDER BY id);
SELECT ROW_NUMBER() OVER w FROM t WINDOW w AS (ORDER BY id);
SELECT * FROM (t1, t2);
SELECT 1 UNION SELECT 2;
SELECT COUNT(*) FROM users;
SELECT COUNT(user_id) FROM orders;
SELECT COUNT(*) FROM orders;
SELECT COUNT(DISTINCT user_id) FROM orders;
SELECT GROUP_CONCAT(name ORDER BY name ASC) FROM users;
SELECT GROUP_CONCAT(name) FROM users;
SELECT SUM(amount) OVER (PARTITION BY user_id) FROM orders;
SELECT GROUP_CONCAT(name SEPARATOR ', ') FROM users;
SELECT GROUP_CONCAT(DISTINCT name ORDER BY name DESC SEPARATOR '|') OVER (PARTITION BY category) FROM products;
SELECT GROUP_CONCAT(DISTINCT name ORDER BY name SEPARATOR ', ') FROM users;
SELECT COUNT(id) FROM users;
SELECT COUNT(DISTINCT id) FROM users;
SELECT GROUP_CONCAT(name ORDER BY name) FROM users;
SELECT * FROM t WHERE a AND b;
SELECT * FROM t WHERE a OR b;
SELECT * FROM t WHERE age > 18;
SELECT * FROM t WHERE age BETWEEN 18 AND 65;
SELECT * FROM t WHERE name IS NULL;
SELECT * FROM t WHERE name IS NOT NULL;
SELECT * FROM t WHERE NOT active;
SELECT * FROM t WHERE id IN (1, 2, 3);
SELECT CONCAT(first_name, ' ', last_name) FROM users;
SELECT * FROM t WHERE (a AND b) OR c;
SELECT * FROM t WHERE EXISTS (SELECT 1 FROM users);
SELECT * FROM users ORDER BY name ASC;
SELECT * FROM users ORDER BY name DESC;
SELECT * FROM users ORDER BY name;
SELECT * FROM users LIMIT 10;
SELECT * FROM users LIMIT 10, 20;
SELECT COUNT(*) FROM users GROUP BY status;
SELECT COUNT(*) as cnt FROM users GROUP BY status HAVING cnt > 5;
SELECT id FROM users;
SELECT id AS user_id FROM users;
SELECT * FROM users;
SELECT * FROM users LIMIT 10 OFFSET 20;
SELECT * FROM users LIMIT 20, 10;
SELECT CASE WHEN age < 13 THEN "child" WHEN age < 18 THEN "teen" WHEN age < 65 THEN "adult" ELSE "senior" END FROM users;
SELECT id INTO @var FROM t;
SELECT COUNT(*) FROM t GROUP BY id HAVING COUNT(*) > 1;
SELECT COUNT(*) FROM t GROUP BY id WITH ROLLUP;
SELECT DATE_ADD('2020-01-01', INTERVAL 1 DAY);
SELECT * FROM t WHERE id = :id;
SELECT * FROM t;
SELECT 'hello';
SELECT 42;
SELECT TRUE;
SELECT NULL;
SELECT UPPER(name) FROM users;
SELECT CASE WHEN age > 18 THEN "adult" ELSE "minor" END FROM users;
SELECT CAST(id AS VARCHAR) FROM users;
SELECT * FROM users AS u;
SELECT * FROM users JOIN orders ON users.id = orders.user_id;
SELECT 1 FROM DUAL;
SELECT NOW() FROM DUAL;
SELECT * FROM mydb.users;
SELECT * FROM users INNER JOIN orders ON users.id = orders.user_id;
SELECT * FROM users INNER JOIN orders USING (user_id);
SELECT * FROM (SELECT id FROM users) AS sub;
SELECT * FROM (SELECT id FROM users);
SELECT 1;
SELECT mydb.UPPER(name) FROM users;
SELECT JSON_EXTRACT(data, "$.name") FROM users;
SELECT CONCAT(first, last) FROM users;
SELECT NOW() FROM dual;
SELECT ROW_NUMBER() OVER (ORDER BY id) FROM users;
SELECT ROW_NUMBER() OVER (PARTITION BY dept ORDER BY salary) FROM employees;
SELECT CURRENT_TIMESTAMP() FROM dual;
SELECT CURRENT_TIMESTAMP;
SELECT * FROM users LEFT JOIN orders ON users.id = orders.user_id;
SELECT * FROM users RIGHT JOIN orders ON users.id = orders.user_id;
SELECT * FROM t WHERE name LIKE "test%";
SELECT * FROM t WHERE name LIKE "test\\\\%" ESCAPE "\\\\";
SELECT * FROM t WHERE name NOT LIKE "test%";
SELECT * FROM t WHERE name LIKE 'test%';
SELECT SUM(amount) OVER (PARTITION BY category, region ORDER BY date) FROM sales;
SELECT (id) AS user_id FROM users;
SELECT mydb.myfunc(id) FROM users;
SELECT * FROM users COLLATE utf8_general_ci;
SELECT id, COUNT(*) FROM users GROUP BY id;
SELECT id, COUNT(*) FROM users GROUP BY id WITH ROLLUP;
SELECT dept, year, COUNT(*) FROM employees GROUP BY dept, year;
SELECT id INTO @var FROM users;
SELECT id FROM users INTO OUTFILE "/tmp/data.txt";
SELECT id FROM users WHERE active = 1 INTO @var;
SELECT 1, 1e1, TRUE, FALSE, 1.1, NULL, "foo", 'bar', `baz`;
WITH cte AS (SELECT id FROM users) SELECT * FROM cte;
SELECT SQL_CALC_FOUND_ROWS * FROM users;
SELECT SQL_CACHE * FROM users;
SELECT SQL_NO_CACHE * FROM users;
SELECT DISTINCT name FROM users;
SELECT * FROM (SELECT id FROM users) AS t;
SELECT * FROM (users, orders);
SELECT * FROM users WHERE id = 1;
SELECT * FROM users WHERE NOT active;
SELECT * FROM users WHERE ISNULL(name);
SELECT dept, COUNT(*) FROM users GROUP BY dept HAVING COUNT(*) > 5;
SELECT id FROM users UNION SELECT id FROM admins;
SELECT id FROM users UNION ALL SELECT id FROM admins;
SELECT * FROM (SELECT * FROM users) AS t;
SELECT * FROM users FOR UPDATE;
SELECT * FROM users LOCK IN SHARE MODE;
SELECT * FROM users FOR UPDATE NOWAIT;
SELECT * FROM users FOR UPDATE SKIP LOCKED;
SELECT * FROM users FOR UPDATE WAIT 5;
SELECT * FROM users for update wait 5;
SELECT id, name FROM users;
SELECT id, (SELECT name FROM users WHERE users.id = t.user_id) as user_name FROM t;
SELECT id, (SELECT name FROM users) as user_name FROM t;
SELECT (SELECT COUNT(*) FROM orders WHERE orders.user_id = u.id) as order_count, (SELECT MAX(created_at) FROM orders WHERE orders.user_id = u.id) as last_order FROM users u;
SELECT * FROM users WHERE id IN (SELECT user_id FROM orders);
SELECT id, (SELECT COUNT(*) FROM orders WHERE user_id = users.id) AS order_count FROM users;
SELECT * FROM users WHERE EXISTS (SELECT 1 FROM orders WHERE user_id = users.id);
SELECT (SELECT id FROM users) AS user_id;
SELECT * FROM users WHERE (id, name) IN (SELECT user_id, user_name FROM orders);
SELECT (SELECT u.id FROM users u JOIN orders o ON u.id = o.user_id) AS data;
SELECT 42 FROM dual;
SELECT TRUE FROM dual;
SELECT * FROM users ORDER BY id + 1 DESC;
SELECT 'hello' FROM dual;
SELECT id FROM users UNION SELECT id FROM customers;
SELECT id FROM users UNION ALL SELECT id FROM customers;
SELECT id FROM users UNION DISTINCT SELECT id FROM customers;
SELECT id FROM users UNION SELECT id FROM customers UNION SELECT id FROM vendors;
SELECT DATE_ADD(NOW(), INTERVAL 1 DAY);
SELECT * FROM users WHERE id = :id;
SELECT @myvar;
SELECT FALSE;
SELECT "hello";
SELECT `hello`;
SELECT :param;
SELECT X'4D7953514C';
SELECT B'1010';
SELECT DATE '2023-01-01';
SELECT TIMESTAMP '2023-01-01 12:00:00';
SELECT TIME '12:00:00';
SELECT N'hello';
SELECT SUM(amount) OVER (ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM orders;
SELECT SUM(amount) OVER (PARTITION BY user_id ORDER BY date) FROM orders;
SELECT SUM(amount) OVER w FROM orders WINDOW w AS (PARTITION BY user_id);
WITH cte (id, name) AS (SELECT id, name FROM users) SELECT * FROM cte;
WITH cte AS (SELECT id, name FROM users) SELECT * FROM cte;
WITH my_cte AS (SELECT 1) SELECT * FROM my_cte;
WITH cte (id, name) AS (SELECT 1, 2) SELECT * FROM cte;
WITH cte AS (SELECT 1, 2) SELECT * FROM cte;
WITH cte1 AS (SELECT 1), cte2 (x) AS (SELECT 2) SELECT * FROM cte1, cte2;
SELECT SQL_SMALL_RESULT * FROM users;
SELECT SQL_BIG_RESULT * FROM users;
SELECT SQL_BUFFER_RESULT * FROM users;
SELECT SUM(amount) OVER (ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) FROM orders;
SELECT * FROM users CROSS JOIN orders;
SELECT id, name, age FROM users;
SELECT DISTINCT id, name FROM users;
SELECT id FROM users GROUP BY id, name;
SELECT * FROM users WHERE id BETWEEN 1 AND 100;
SELECT * FROM users WHERE name LIKE 'John%';
SELECT * FROM users WHERE id NOT IN (1, 2, 3);
SELECT * FROM users WHERE age >= 18 AND status = 'active';
SELECT COALESCE(name, 'Unknown') FROM users;
SELECT IFNULL(email, 'no-email') FROM users;
SELECT IF(age > 18, 'adult', 'minor') FROM users;
SELECT * FROM users FULL JOIN orders ON users.id = orders.user_id;
SELECT * FROM users FULL OUTER JOIN orders ON users.id = orders.user_id;
SELECT * FROM users STRAIGHT_JOIN orders ON users.id = orders.user_id;
SELECT * FROM users LEFT OUTER JOIN orders ON users.id = orders.user_id;
SELECT * FROM users RIGHT OUTER JOIN orders ON users.id = orders.user_id;
SELECT * FROM users, LATERAL (SELECT * FROM orders WHERE orders.user_id = users.id) AS o;
SELECT * FROM (VALUES ROW(1, 2), ROW(3, 4)) AS t;
WITH RECURSIVE cte AS (SELECT 1 AS n UNION ALL SELECT n + 1 FROM cte WHERE n < 5) SELECT * FROM cte;
SELECT * FROM users WHERE name REGEXP '^[A-Z]';
SELECT * FROM users WHERE name NOT REGEXP '^[A-Z]';
SELECT * FROM users WHERE name RLIKE '^test';
SELECT * FROM users WHERE name REGEXP BINARY '^test';
SELECT * FROM users WHERE id <> 5;
SELECT * FROM users WHERE id != 5;
SELECT * FROM users WHERE age >= 18 AND age <= 65;
SELECT * FROM users WHERE status IN ('active', 'pending');
SELECT * FROM users WHERE status NOT IN ('deleted', 'banned');
SELECT * FROM users WHERE NOT EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id);
SELECT AVG(price) FROM products;
SELECT MIN(price) FROM products;
SELECT MAX(price) FROM products;
SELECT AVG(price) OVER (PARTITION BY category) FROM products;
SELECT MIN(price) OVER (ORDER BY id) FROM products;
SELECT MAX(price) OVER () FROM products;
SELECT RANK() OVER (ORDER BY salary DESC) FROM employees;
SELECT DENSE_RANK() OVER (ORDER BY score) FROM students;
SELECT LAG(salary, 1) OVER (ORDER BY hire_date) FROM employees;
SELECT LEAD(salary, 1, 0) OVER (ORDER BY hire_date) FROM employees;
SELECT FIRST_VALUE(name) OVER (ORDER BY id) FROM users;
SELECT LAST_VALUE(name) OVER (ORDER BY id) FROM users;
SELECT NTILE(4) OVER (ORDER BY salary) FROM employees;
SELECT PERCENT_RANK() OVER (ORDER BY score) FROM students;
SELECT CUME_DIST() OVER (ORDER BY score) FROM students;
SELECT EXTRACT(YEAR FROM created_at) FROM orders;
SELECT TRIM(LEADING ' ' FROM name) FROM users;
SELECT TRIM(TRAILING ' ' FROM name) FROM users;
SELECT TRIM(BOTH ' ' FROM name) FROM users;
SELECT TRIM(' ' FROM name) FROM users;
SELECT CONVERT(id, CHAR) FROM users;
SELECT CONVERT(id USING utf8) FROM users;
SELECT TIMESTAMPDIFF(DAY, start_date, end_date) FROM events;
SELECT TIMESTAMPADD(HOUR, 2, created_at) FROM orders;
SELECT CURRENT_USER();
SELECT SESSION_USER();
SELECT SYSTEM_USER();
SELECT USER();
SELECT id FROM users INTERSECT SELECT id FROM customers;
SELECT id FROM users EXCEPT SELECT id FROM banned_users;
SELECT id FROM users MINUS SELECT id FROM deleted_users;
SELECT * FROM users WHERE id = ANY (SELECT user_id FROM orders);
SELECT * FROM users WHERE id = SOME (SELECT user_id FROM orders);
SELECT * FROM users WHERE id = ALL (SELECT user_id FROM banned_users);
SELECT * FROM users WHERE id > ANY (SELECT user_id FROM orders);
SELECT * FROM users WHERE id < ALL (SELECT user_id FROM orders);
SELECT * FROM t1 LEFT JOIN t2 ON t1.id = t2.id LEFT JOIN t3 ON t2.id = t3.id;
SELECT * FROM t1, t2, t3 WHERE t1.id = t2.id AND t2.id = t3.id;
SELECT id DIV 10 FROM users;
SELECT id MOD 3 FROM users;
SELECT id % 3 FROM users;
SELECT id & 255 FROM users;
SELECT id | 128 FROM users;
SELECT id ^ 15 FROM users;
SELECT id << 2 FROM users;
SELECT id >> 2 FROM users;
SELECT ~id FROM users;
SELECT id XOR 1 FROM users;
SELECT * FROM users WHERE name LIKE 'test%' ESCAPE '\\';
SELECT * FROM users WHERE name NOT LIKE 'test%' ESCAPE '\\';
SELECT * FROM users WHERE name REGEXP 'test';
SELECT * FROM users WHERE name NOT REGEXP 'test';
SELECT * FROM users WHERE name RLIKE 'test';
SELECT * FROM users WHERE name NOT RLIKE 'test';
SELECT * FROM users WHERE id IN (1, 2, 3);
SELECT * FROM users WHERE id NOT IN (1, 2, 3);
SELECT * FROM users WHERE id IN (SELECT user_id FROM orders);
SELECT * FROM users WHERE id NOT IN (SELECT user_id FROM orders);
SELECT * FROM users WHERE id IN @var;
SELECT * FROM users WHERE id NOT IN @var;
SELECT * FROM users WHERE age BETWEEN 18 AND 65;
SELECT * FROM users WHERE age NOT BETWEEN 18 AND 65;
SELECT * FROM users WHERE id IS NULL;
SELECT * FROM users WHERE id IS NOT NULL;
SELECT * FROM users WHERE EXISTS (SELECT 1 FROM orders WHERE user_id = users.id);
SELECT * FROM users WHERE NOT EXISTS (SELECT 1 FROM orders WHERE user_id = users.id);
SELECT * FROM users WHERE id = 1 AND name = 'test';
SELECT * FROM users WHERE id = 1 OR name = 'test';
SELECT * FROM users WHERE NOT id = 1;
SELECT * FROM users WHERE id > 10;
SELECT * FROM users WHERE id >= 10;
SELECT * FROM users WHERE id < 10;
SELECT * FROM users WHERE id <= 10;
SELECT * FROM users WHERE id = 10;
SELECT * FROM users WHERE id <> 10;
SELECT * FROM users WHERE id != 10;
SELECT * FROM users WHERE id + 5 > 10;
SELECT * FROM users WHERE id - 5 > 10;
SELECT * FROM users WHERE id * 2 > 10;
SELECT * FROM users WHERE id / 2 > 10;
SELECT * FROM users WHERE id % 2 = 0;
SELECT * FROM users WHERE id DIV 2 = 5;
SELECT * FROM users WHERE id MOD 2 = 0;
SELECT * FROM users WHERE id & 1 = 1;
SELECT * FROM users WHERE id | 1 = 1;
SELECT * FROM users WHERE id ^ 1 = 1;
SELECT * FROM users WHERE id << 1 = 2;
SELECT * FROM users WHERE id >> 1 = 5;
SELECT * FROM users WHERE ~id = -2;
SELECT * FROM users WHERE id XOR 1 = 0;
SELECT * FROM users WHERE id || 1 = 11;
SELECT * FROM users WHERE id && 1 = 1;
SELECT -id FROM users;
SELECT +id FROM users;
SELECT !active FROM users;
SELECT ~flags FROM users;
SELECT * FROM users ORDER BY id ASC;
SELECT * FROM users ORDER BY id DESC;
SELECT * FROM users ORDER BY id ASC, name DESC;
SELECT * FROM users ORDER BY id;
SELECT * FROM users LIMIT 10;
SELECT * FROM users LIMIT 10 OFFSET 5;
SELECT * FROM users LIMIT 5, 10;
SELECT * FROM users GROUP BY status;
SELECT * FROM users GROUP BY status, role;
SELECT * FROM users GROUP BY status WITH ROLLUP;
SELECT * FROM users HAVING COUNT(*) > 5;
SELECT * FROM users GROUP BY status HAVING COUNT(*) > 5;
SELECT * FROM users WHERE id > 10 GROUP BY status HAVING COUNT(*) > 5 ORDER BY status LIMIT 10;
SELECT DISTINCT id FROM users;
SELECT * FROM users;
SELECT id, name FROM users;
SELECT users.id FROM users;
SELECT u.id FROM users u;
SELECT users.* FROM users;
SELECT u.* FROM users u;
SELECT db.users.id FROM db.users;
SELECT * FROM users AS u;
SELECT * FROM users u;
SELECT * FROM (SELECT id FROM users) AS sub;
SELECT * FROM (SELECT id FROM users) sub;
SELECT * FROM users JOIN orders ON users.id = orders.user_id;
SELECT * FROM users INNER JOIN orders ON users.id = orders.user_id;
SELECT * FROM users LEFT JOIN orders ON users.id = orders.user_id;
SELECT * FROM users LEFT OUTER JOIN orders ON users.id = orders.user_id;
SELECT * FROM users RIGHT JOIN orders ON users.id = orders.user_id;
SELECT * FROM users RIGHT OUTER JOIN orders ON users.id = orders.user_id;
SELECT * FROM users FULL JOIN orders ON users.id = orders.user_id;
SELECT * FROM users FULL OUTER JOIN orders ON users.id = orders.user_id;
SELECT * FROM users CROSS JOIN orders;
SELECT * FROM users STRAIGHT_JOIN orders ON users.id = orders.user_id;
SELECT * FROM users JOIN orders USING (user_id);
SELECT * FROM users, orders;
SELECT * FROM users, orders, products;
SELECT * FROM (users, orders);
SELECT * FROM ((users, orders));
SELECT * FROM users JOIN orders ON users.id = orders.user_id JOIN products ON orders.product_id = products.id;
SELECT * FROM DUAL;
SELECT 1 FROM DUAL;
SELECT NOW() FROM DUAL;
SELECT * FROM LATERAL (SELECT * FROM orders WHERE user_id = 1) AS o;
SELECT * FROM users, LATERAL (SELECT * FROM orders WHERE orders.user_id = users.id) AS o;
SELECT * FROM (VALUES ROW(1, 2), ROW(3, 4)) AS t;
SELECT * FROM (VALUES (1, 2), (3, 4)) AS t;
WITH cte AS (SELECT id FROM users) SELECT * FROM cte;
WITH cte (id, name) AS (SELECT id, name FROM users) SELECT * FROM cte;
WITH cte1 AS (SELECT 1), cte2 AS (SELECT 2) SELECT * FROM cte1, cte2;
WITH RECURSIVE cte AS (SELECT 1 AS n UNION ALL SELECT n + 1 FROM cte WHERE n < 5) SELECT * FROM cte;
SELECT * FROM users UNION SELECT * FROM customers;
SELECT * FROM users UNION ALL SELECT * FROM customers;
SELECT * FROM users UNION DISTINCT SELECT * FROM customers;
SELECT * FROM users INTERSECT SELECT * FROM customers;
SELECT * FROM users EXCEPT SELECT * FROM customers;
SELECT * FROM users MINUS SELECT * FROM customers;
SELECT * FROM users UNION SELECT * FROM customers ORDER BY id;
SELECT * FROM users UNION SELECT * FROM customers LIMIT 10;
SELECT * FROM users UNION SELECT * FROM customers ORDER BY id LIMIT 10;
SELECT (SELECT id FROM users LIMIT 1) AS user_id;
SELECT * FROM (SELECT id FROM users UNION SELECT id FROM customers) AS combined;
SELECT id INTO @var FROM users;
SELECT id, name INTO @id, @name FROM users;
SELECT id INTO OUTFILE '/tmp/data.txt' FROM users;
SELECT id INTO DUMPFILE '/tmp/data.txt' FROM users;
SELECT id FROM users INTO @var;
SELECT id FROM users INTO OUTFILE '/tmp/data.txt';
SELECT id FROM users INTO DUMPFILE '/tmp/data.txt';
SELECT id, name FROM users INTO @id, @name;
SELECT * FROM users FOR UPDATE;
SELECT * FROM users FOR UPDATE NOWAIT;
SELECT * FROM users FOR UPDATE SKIP LOCKED;
SELECT * FROM users FOR UPDATE WAIT 10;
SELECT * FROM users LOCK IN SHARE MODE;
SELECT * FROM users LOCK IN SHARE MODE NOWAIT;
SELECT * FROM users LOCK IN SHARE MODE SKIP LOCKED;
SELECT * FROM users LOCK IN SHARE MODE WAIT 10;
SELECT SQL_CALC_FOUND_ROWS * FROM users;
SELECT SQL_CACHE * FROM users;
SELECT SQL_NO_CACHE * FROM users;
SELECT SQL_SMALL_RESULT * FROM users;
SELECT SQL_BIG_RESULT * FROM users;
SELECT SQL_BUFFER_RESULT * FROM users;
SELECT SQL_CALC_FOUND_ROWS SQL_CACHE * FROM users;
SELECT COUNT(*) FROM users;
SELECT COUNT(id) FROM users;
SELECT COUNT(DISTINCT id) FROM users;
SELECT COUNT(*) OVER () FROM users;
SELECT COUNT(*) OVER (PARTITION BY status) FROM users;
SELECT COUNT(*) OVER (ORDER BY id) FROM users;
SELECT COUNT(*) OVER (PARTITION BY status ORDER BY id) FROM users;
SELECT SUM(amount) FROM orders;
SELECT SUM(amount) OVER () FROM orders;
SELECT SUM(amount) OVER (PARTITION BY user_id) FROM orders;
SELECT SUM(amount) OVER (ORDER BY date) FROM orders;
SELECT SUM(amount) OVER (PARTITION BY user_id ORDER BY date) FROM orders;
SELECT AVG(price) FROM products;
SELECT AVG(price) OVER () FROM products;
SELECT AVG(price) OVER (PARTITION BY category) FROM products;
SELECT MIN(price) FROM products;
SELECT MIN(price) OVER () FROM products;
SELECT MIN(price) OVER (PARTITION BY category) FROM products;
SELECT MAX(price) FROM products;
SELECT MAX(price) OVER () FROM products;
SELECT MAX(price) OVER (PARTITION BY category) FROM products;
SELECT GROUP_CONCAT(name) FROM users;
SELECT GROUP_CONCAT(name SEPARATOR ', ') FROM users;
SELECT GROUP_CONCAT(DISTINCT name) FROM users;
SELECT GROUP_CONCAT(name ORDER BY name) FROM users;
SELECT GROUP_CONCAT(name ORDER BY name ASC) FROM users;
SELECT GROUP_CONCAT(name ORDER BY name DESC) FROM users;
SELECT GROUP_CONCAT(DISTINCT name ORDER BY name) FROM users;
SELECT GROUP_CONCAT(DISTINCT name ORDER BY name SEPARATOR ', ') FROM users;
SELECT GROUP_CONCAT(name) OVER (PARTITION BY status) FROM users;
SELECT ROW_NUMBER() OVER (ORDER BY id) FROM users;
SELECT ROW_NUMBER() OVER (PARTITION BY dept ORDER BY salary) FROM employees;
SELECT RANK() OVER (ORDER BY score) FROM students;
SELECT DENSE_RANK() OVER (ORDER BY score) FROM students;
SELECT PERCENT_RANK() OVER (ORDER BY score) FROM students;
SELECT CUME_DIST() OVER (ORDER BY score) FROM students;
SELECT NTILE(4) OVER (ORDER BY salary) FROM employees;
SELECT LAG(salary) OVER (ORDER BY hire_date) FROM employees;
SELECT LAG(salary, 1) OVER (ORDER BY hire_date) FROM employees;
SELECT LAG(salary, 1, 0) OVER (ORDER BY hire_date) FROM employees;
SELECT LEAD(salary) OVER (ORDER BY hire_date) FROM employees;
SELECT LEAD(salary, 1) OVER (ORDER BY hire_date) FROM employees;
SELECT LEAD(salary, 1, 0) OVER (ORDER BY hire_date) FROM employees;
SELECT FIRST_VALUE(name) OVER (ORDER BY id) FROM users;
SELECT LAST_VALUE(name) OVER (ORDER BY id) FROM users;
SELECT NTH_VALUE(name, 2) OVER (ORDER BY id) FROM users;
SELECT * FROM users WINDOW w AS (ORDER BY id);
SELECT * FROM users WINDOW w AS (PARTITION BY status ORDER BY id);
SELECT ROW_NUMBER() OVER w FROM users WINDOW w AS (ORDER BY id);
SELECT ROW_NUMBER() OVER w FROM users WINDOW w AS (PARTITION BY status ORDER BY id);
SELECT id, ROW_NUMBER() OVER w FROM users WINDOW w AS (ORDER BY id);
SELECT * FROM users WINDOW w1 AS (ORDER BY id), w2 AS (PARTITION BY status);
SELECT SUM(amount) OVER (ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM orders;
SELECT SUM(amount) OVER (ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) FROM orders;
SELECT SUM(amount) OVER (ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) FROM orders;
SELECT SUM(amount) OVER (ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) FROM orders;
SELECT SUM(amount) OVER (ROWS BETWEEN CURRENT ROW AND 2 FOLLOWING) FROM orders;
SELECT SUM(amount) OVER (ROWS UNBOUNDED PRECEDING) FROM orders;
SELECT SUM(amount) OVER (ROWS 1 PRECEDING) FROM orders;
SELECT SUM(amount) OVER (ROWS CURRENT ROW) FROM orders;
SELECT SUM(amount) OVER (ROWS 1 FOLLOWING) FROM orders;
SELECT SUM(amount) OVER (ROWS UNBOUNDED FOLLOWING) FROM orders;
SELECT UPPER(name) FROM users;
SELECT LOWER(name) FROM users;
SELECT CONCAT(first_name, ' ', last_name) FROM users;
SELECT SUBSTRING(name, 1, 5) FROM users;
SELECT LENGTH(name) FROM users;
SELECT TRIM(name) FROM users;
SELECT TRIM(LEADING ' ' FROM name) FROM users;
SELECT TRIM(TRAILING ' ' FROM name) FROM users;
SELECT TRIM(BOTH ' ' FROM name) FROM users;
SELECT TRIM(' ' FROM name) FROM users;
SELECT LTRIM(name) FROM users;
SELECT RTRIM(name) FROM users;
SELECT REPLACE(name, 'old', 'new') FROM users;
SELECT COALESCE(name, 'Unknown') FROM users;
SELECT IFNULL(name, 'Unknown') FROM users;
SELECT NULLIF(name, '') FROM users;
SELECT IF(age > 18, 'adult', 'minor') FROM users;
SELECT NOW() FROM users;
SELECT CURRENT_DATE FROM users;
SELECT CURRENT_TIME FROM users;
SELECT CURRENT_TIMESTAMP FROM users;
SELECT USER() FROM users;
SELECT SESSION_USER() FROM users;
SELECT SYSTEM_USER() FROM users;
SELECT CURRENT_USER() FROM users;
SELECT DATE_ADD(created_at, INTERVAL 1 DAY) FROM users;
SELECT DATE_SUB(created_at, INTERVAL 1 MONTH) FROM users;
SELECT ADDDATE(created_at, INTERVAL 1 YEAR) FROM users;
SELECT TIMESTAMPDIFF(DAY, start_date, end_date) FROM events;
SELECT TIMESTAMPADD(HOUR, 2, created_at) FROM orders;
SELECT EXTRACT(YEAR FROM created_at) FROM orders;
SELECT EXTRACT(MONTH FROM created_at) FROM orders;
SELECT EXTRACT(DAY FROM created_at) FROM orders;
SELECT EXTRACT(HOUR FROM created_at) FROM orders;
SELECT EXTRACT(MINUTE FROM created_at) FROM orders;
SELECT EXTRACT(SECOND FROM created_at) FROM orders;
SELECT DATE_TRUNC(created_at, MONTH) FROM orders;
SELECT CAST(id AS CHAR) FROM users;
SELECT CAST(id AS VARCHAR) FROM users;
SELECT CAST(id AS INT) FROM users;
SELECT CAST(id AS INTEGER) FROM users;
SELECT CAST(id AS SIGNED) FROM users;
SELECT CAST(id AS UNSIGNED) FROM users;
SELECT CAST(id AS SIGNED INTEGER) FROM users;
SELECT CAST(id AS UNSIGNED INTEGER) FROM users;
SELECT CAST(price AS DECIMAL) FROM products;
SELECT CAST(price AS DECIMAL(10)) FROM products;
SELECT CAST(price AS DECIMAL(10, 2)) FROM products;
SELECT CAST(created_at AS DATE) FROM orders;
SELECT CAST(created_at AS DATETIME) FROM orders;
SELECT CAST(created_at AS TIME) FROM orders;
SELECT CAST(created_at AS TIMESTAMP) FROM orders;
SELECT CAST(data AS JSON) FROM logs;
SELECT CONVERT(id, CHAR) FROM users;
SELECT CONVERT(id, SIGNED) FROM users;
SELECT CONVERT(id, UNSIGNED) FROM users;
SELECT CONVERT(id USING utf8) FROM users;
SELECT CASE WHEN age < 18 THEN 'minor' ELSE 'adult' END FROM users;
SELECT CASE WHEN age < 13 THEN 'child' WHEN age < 18 THEN 'teen' ELSE 'adult' END FROM users;
SELECT CASE status WHEN 'active' THEN 1 WHEN 'inactive' THEN 0 END FROM users;
SELECT CASE status WHEN 'active' THEN 1 WHEN 'inactive' THEN 0 ELSE -1 END FROM users;
SELECT INTERVAL 1 DAY;
SELECT INTERVAL 1 MONTH;
SELECT INTERVAL 1 YEAR;
SELECT INTERVAL 1 HOUR;
SELECT INTERVAL 1 MINUTE;
SELECT INTERVAL 1 SECOND;
SELECT INTERVAL '1:30' HOUR_MINUTE;
SELECT INTERVAL '1 2:30:45' DAY_SECOND;
SELECT 1;
SELECT 1.5;
SELECT 1e10;
SELECT 1.5e10;
SELECT -1;
SELECT +1;
SELECT 0x1A;
SELECT X'4D7953514C';
SELECT B'1010';
SELECT 0b1010;
SELECT TRUE;
SELECT FALSE;
SELECT NULL;
SELECT 'string';
SELECT "string";
SELECT `identifier`;
SELECT N'unicode';
SELECT _binary'binary';
SELECT _latin1'latin1';
SELECT DATE '2023-01-01';
SELECT TIME '12:00:00';
SELECT TIMESTAMP '2023-01-01 12:00:00';
SELECT DATETIME '2023-01-01 12:00:00';
SELECT @var;
SELECT @@global.var;
SELECT @@session.var;
SELECT :param;
SELECT ?;
SELECT (1);
SELECT (1 + 2);
SELECT ((1 + 2) * 3);
SELECT * FROM users COLLATE utf8_general_ci;
SELECT name COLLATE utf8_bin FROM users;
SELECT * FROM users WHERE name COLLATE utf8_bin = 'test';
SELECT MATCH(title, body) AGAINST ('search term') FROM articles;
SELECT MATCH(title, body) AGAINST ('search term' IN NATURAL LANGUAGE MODE) FROM articles;
SELECT MATCH(title, body) AGAINST ('search term' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION) FROM articles;
SELECT MATCH(title, body) AGAINST ('search term' IN BOOLEAN MODE) FROM articles;
SELECT MATCH(title, body) AGAINST ('search term' WITH QUERY EXPANSION) FROM articles;
SELECT MATCH(title) AGAINST ('search') AS score FROM articles;
SELECT * FROM articles WHERE MATCH(title, body) AGAINST ('search term');
SELECT *, MATCH(title, body) AGAINST ('search') AS score FROM articles WHERE MATCH(title, body) AGAINST ('search');
SELECT JSON_EXTRACT(data, '$.name') FROM users;
SELECT data->'$.name' FROM users;
SELECT data->>'$.name' FROM users;
SELECT * FROM users WHERE data->'$.age' > 18;
SELECT * FROM users WHERE data->>'$.name' = 'John';
SELECT * FROM db.table;
SELECT mydb.myfunc(id) FROM users;
SELECT schema.myfunc(id) FROM users;
SELECT (SELECT 1);
SELECT (SELECT 1 FROM users);
SELECT (SELECT id FROM users WHERE id = 1);
SELECT * FROM users WHERE id = (SELECT MAX(id) FROM orders);
SELECT * FROM users WHERE (id, name) = (SELECT user_id, user_name FROM orders LIMIT 1);
SELECT * FROM users WHERE id = ANY (SELECT user_id FROM orders);
SELECT * FROM users WHERE id = SOME (SELECT user_id FROM orders);
SELECT * FROM users WHERE id = ALL (SELECT user_id FROM orders);
SELECT * FROM users WHERE id > ANY (SELECT user_id FROM orders);
SELECT * FROM users WHERE id < ALL (SELECT user_id FROM orders);
SELECT * FROM users WHERE id >= ANY (SELECT user_id FROM orders);
SELECT * FROM users WHERE id <= ALL (SELECT user_id FROM orders);
SELECT * FROM users WHERE id <> ANY (SELECT user_id FROM orders);
SELECT * FROM users WHERE id != ALL (SELECT user_id FROM orders);
SELECT id, (SELECT COUNT(*) FROM orders WHERE user_id = users.id) AS order_count FROM users;
SELECT id, (SELECT name FROM profiles WHERE user_id = users.id) AS profile_name FROM users;
SELECT (SELECT COUNT(*) FROM orders) AS total_orders;
SELECT * FROM (SELECT * FROM users WHERE active = 1) AS active_users;
SELECT * FROM (SELECT id, name FROM users UNION SELECT id, name FROM customers) AS combined;
SELECT * FROM ((SELECT id FROM users));
SELECT * FROM (((SELECT id FROM users)));
SELECT SQL_CALC_FOUND_ROWS SQL_CACHE SQL_SMALL_RESULT * FROM users;
SELECT SQL_CALC_FOUND_ROWS SQL_NO_CACHE SQL_BIG_RESULT * FROM users;
SELECT SQL_BUFFER_RESULT SQL_SMALL_RESULT * FROM users;
SELECT CASE WHEN (id, name) IN (SELECT user_id, user_name FROM orders) THEN 'found' END FROM users;
SELECT CASE status WHEN 'active' THEN 1 WHEN 'pending' THEN 2 WHEN 'inactive' THEN 0 ELSE -1 END FROM users;
SELECT CASE WHEN id > 10 AND status = 'active' THEN 'valid' ELSE 'invalid' END FROM users;
SELECT CASE WHEN id IN (1, 2, 3) OR name LIKE 'test%' THEN 'match' END FROM users;
SELECT CASE type WHEN 1 THEN 'type1' WHEN 2 THEN 'type2' WHEN 3 THEN 'type3' END FROM items;
SELECT CASE WHEN EXISTS (SELECT 1 FROM orders WHERE user_id = users.id) THEN 'has_orders' ELSE 'no_orders' END FROM users;
SELECT CASE WHEN age BETWEEN 18 AND 65 THEN 'working_age' ELSE 'other' END FROM users;
SELECT CASE WHEN NOT active THEN 'inactive' WHEN verified THEN 'verified' ELSE 'pending' END FROM users;
SELECT EXTRACT(YEAR FROM created_at) FROM users;
