UPDATE users SET name = "John" WHERE id = 1;
UPDATE users SET users.name = "John" WHERE id = 1;
UPDATE t1, DUAL SET t1.col = 1;
UPDATE users SET name = "John", age = 30;
WITH cte AS (SELECT id FROM temp) UPDATE users SET name = "John" WHERE id IN (SELECT id FROM cte);
UPDATE users SET name = "John";
UPDATE users u JOIN orders o ON u.id = o.user_id SET u.name = "John";
UPDATE users SET name = "John", age = 30, email = "john@example.com";
UPDATE users SET name = "John" WHERE NOT active;
UPDATE users SET name = "John" WHERE ISNULL(deleted_at);
UPDATE users SET name = "John" ORDER BY id DESC;
UPDATE users SET name = "John" LIMIT 10;
UPDATE users SET name = 'Jane' WHERE id = 1;
UPDATE users SET name = 'Jane', age = 30 WHERE id = 1;
UPDATE users SET status = 'active' WHERE created_at < NOW();
UPDATE users SET counter = counter + 1 WHERE id = 1;
UPDATE users SET name = UPPER(name);
UPDATE users SET updated_at = CURRENT_TIMESTAMP WHERE id = 1;
UPDATE users SET name = "John" WHERE id = 1 ORDER BY created_at LIMIT 5;
UPDATE users SET name = "John" ORDER BY id ASC LIMIT 100;
UPDATE users LEFT JOIN orders ON users.id = orders.user_id SET users.status = 'active';
UPDATE users RIGHT JOIN orders ON users.id = orders.user_id SET users.status = 'active';
UPDATE users INNER JOIN orders ON users.id = orders.user_id SET users.status = 'active';
UPDATE users CROSS JOIN orders SET users.status = 'active';
UPDATE users STRAIGHT_JOIN orders SET users.status = 'active';
UPDATE t1, t2 SET t1.col = t2.col WHERE t1.id = t2.id;
UPDATE t1, t2, t3 SET t1.col = 1, t2.col = 2, t3.col = 3;
UPDATE users SET col = VALUES(col);
UPDATE db.users SET name = "John";
UPDATE users SET name = "John" WHERE id IN (SELECT id FROM temp);
UPDATE users SET name = "John" WHERE id = (SELECT MAX(id) FROM temp);
UPDATE users SET name = "John" WHERE EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id);
UPDATE users SET name = "John" WHERE id BETWEEN 1 AND 100;
UPDATE users SET name = "John" WHERE name LIKE 'J%';
UPDATE users SET name = "John" WHERE name REGEXP '^J';
UPDATE users SET name = "John" WHERE id IS NULL;
UPDATE users SET name = "John" WHERE id IS NOT NULL;
UPDATE users SET name = "John" WHERE active = TRUE;
UPDATE users SET name = "John" WHERE active = FALSE;
UPDATE users SET name = "John" WHERE id > 10 AND status = 'active';
UPDATE users SET name = "John" WHERE id > 10 OR status = 'active';
UPDATE users SET name = "John" WHERE NOT (id > 10);
UPDATE users SET name = "John" WHERE id >= 10;
UPDATE users SET name = "John" WHERE id <= 10;
UPDATE users SET name = "John" WHERE id <> 10;
UPDATE users SET name = "John" WHERE id != 10;
UPDATE users SET score = score + 10;
UPDATE users SET score = score - 10;
UPDATE users SET score = score * 2;
UPDATE users SET score = score / 2;
UPDATE users SET score = score % 3;
UPDATE users SET score = score DIV 2;
UPDATE users SET score = score MOD 3;
UPDATE users SET flags = flags | 1;
UPDATE users SET flags = flags & 1;
UPDATE users SET flags = flags ^ 1;
UPDATE users SET flags = flags << 1;
UPDATE users SET flags = flags >> 1;
UPDATE users SET name = CONCAT(first_name, ' ', last_name);
UPDATE users SET age = YEAR(CURRENT_DATE) - YEAR(birth_date);
UPDATE users SET name = CASE WHEN age > 18 THEN 'Adult' ELSE 'Minor' END;
UPDATE users SET name = CASE age WHEN 18 THEN 'Eighteen' WHEN 21 THEN 'TwentyOne' ELSE 'Other' END;
UPDATE users SET name = CAST(id AS CHAR);
UPDATE users SET name = CONVERT(id, CHAR);
UPDATE users SET created_at = CURRENT_TIMESTAMP;
UPDATE users SET created_at = CURRENT_DATE;
UPDATE users SET created_at = CURRENT_TIME;
UPDATE users SET name = TRIM(name);
UPDATE users SET name = TRIM(LEADING ' ' FROM name);
UPDATE users SET name = TRIM(TRAILING ' ' FROM name);
UPDATE users SET name = TRIM(BOTH ' ' FROM name);
UPDATE users SET date_col = DATE_ADD(date_col, INTERVAL 1 DAY);
UPDATE users SET date_col = date_col + INTERVAL 1 HOUR;
UPDATE users SET name = SUBSTRING(name, 1, 10);
UPDATE users SET name = COALESCE(nickname, name, 'Unknown');
UPDATE users SET name = NULLIF(name, '');
UPDATE users SET name = IF(age > 18, 'Adult', 'Minor');
UPDATE users SET name = IFNULL(nickname, name);
UPDATE users SET score = GREATEST(score1, score2, score3);
UPDATE users SET score = LEAST(score1, score2, score3);
UPDATE users SET name = LOWER(name);
UPDATE users SET name = REPLACE(name, 'old', 'new');
UPDATE users SET name = REVERSE(name);
UPDATE users SET total = (SELECT SUM(amount) FROM orders WHERE orders.user_id = users.id);
UPDATE users SET name = "John" LIMIT 10 OFFSET 5;
UPDATE users SET name = "John" LIMIT 5, 10;
UPDATE users SET name = "John" WHERE id IN (1, 2, 3, 4, 5);
UPDATE users SET name = "John" WHERE (id > 10 AND status = 'active') OR (id < 5 AND status = 'pending');
UPDATE users SET name = NULL;
UPDATE users SET name = 'O\'Reilly';
UPDATE users SET name = "He said \"Hello\"";
UPDATE users SET data = X'48656C6C6F';
UPDATE users SET data = 0x48656C6C6F;
UPDATE users SET flags = b'1010';
UPDATE users SET name = N'Unicode';
UPDATE users SET created_at = TIMESTAMP '2023-01-01 00:00:00';
UPDATE users SET created_at = DATE '2023-01-01';
UPDATE users SET created_at = TIME '12:00:00';
UPDATE users SET score = 123;
UPDATE users SET score = 123.45;
UPDATE users SET score = -123;
UPDATE users SET score = +123;
UPDATE users SET score = 1.23e10;
UPDATE users SET score = 1.23E-10;
UPDATE users SET name = "John" WHERE id = ?;
UPDATE users SET name = ? WHERE id = ?;
UPDATE users SET name = :param1 WHERE id = :param2;
WITH RECURSIVE cte AS (SELECT 1 AS n UNION ALL SELECT n + 1 FROM cte WHERE n < 10) UPDATE users SET level = (SELECT n FROM cte WHERE cte.n = users.id);
UPDATE users u1 LEFT JOIN users u2 ON u1.manager_id = u2.id SET u1.manager_name = u2.name;
UPDATE users u1 RIGHT JOIN users u2 ON u1.manager_id = u2.id SET u1.manager_name = u2.name;
UPDATE users u1 INNER JOIN users u2 ON u1.manager_id = u2.id SET u1.manager_name = u2.name;
UPDATE users u1 CROSS JOIN users u2 SET u1.col = u2.col;
UPDATE users JOIN orders USING (user_id) SET users.order_count = orders.count;
UPDATE users LEFT JOIN orders USING (user_id) SET users.order_count = orders.count;
UPDATE (SELECT * FROM users WHERE active = 1) AS u SET u.name = "John";
UPDATE users SET name = "John" WHERE id = 1 AND status = 'active' ORDER BY created_at DESC LIMIT 1;
UPDATE t1 SET col1 = (col2 + col3) * col4;
UPDATE users SET name = "John" WHERE MATCH(name, description) AGAINST('search term');
UPDATE users SET name = "John" WHERE MATCH(name) AGAINST('search term' IN NATURAL LANGUAGE MODE);
UPDATE users SET name = "John" WHERE MATCH(name) AGAINST('search term' IN BOOLEAN MODE);
UPDATE users SET name = "John" WHERE MATCH(name) AGAINST('search term' WITH QUERY EXPANSION);
UPDATE users SET json_col = JSON_SET(json_col, '$.key', 'value');
UPDATE users SET array_col = JSON_ARRAY(1, 2, 3);
UPDATE users SET obj_col = JSON_OBJECT('key', 'value');
UPDATE users SET name = "John" WHERE json_col->'$.key' = 'value';
UPDATE users SET name = "John" WHERE json_col->>'$.key' = 'value';
UPDATE users SET name = "John" WHERE id = ALL(SELECT id FROM temp);
UPDATE users SET name = "John" WHERE id = ANY(SELECT id FROM temp);
UPDATE users SET name = "John" WHERE id = SOME(SELECT id FROM temp);
UPDATE users SET bit_col = bit_col & ~1;
UPDATE users SET bit_col = ~bit_col;
UPDATE users SET name = "John" WHERE name COLLATE utf8mb4_general_ci = 'john';
UPDATE users SET name = "John" COLLATE utf8mb4_bin;
UPDATE users SET name = EXTRACT(YEAR FROM created_at);
UPDATE users SET name = EXTRACT(MONTH FROM created_at);
UPDATE users SET name = EXTRACT(DAY FROM created_at);
UPDATE users SET name = DATE_FORMAT(created_at, '%Y-%m-%d');
UPDATE users SET name = STR_TO_DATE('2023-01-01', '%Y-%m-%d');
UPDATE users SET duration = TIMESTAMPDIFF(DAY, start_date, end_date);
UPDATE users SET future_date = TIMESTAMPADD(DAY, 7, created_at);
UPDATE users SET name = CHAR(65, 66, 67);
UPDATE users SET name = CONCAT_WS(',', first_name, last_name);
UPDATE users SET hash = MD5(password);
UPDATE users SET hash = SHA1(password);
UPDATE users SET hash = SHA2(password, 256);
UPDATE users SET random_val = RAND();
UPDATE users SET random_val = FLOOR(RAND() * 100);
UPDATE users SET rounded = ROUND(score, 2);
UPDATE users SET ceiled = CEIL(score);
UPDATE users SET floored = FLOOR(score);
UPDATE users SET absolute = ABS(score);
UPDATE users SET powered = POW(score, 2);
UPDATE users SET rooted = SQRT(score);
UPDATE users SET name = LPAD(name, 10, '0');
UPDATE users SET name = RPAD(name, 10, '0');
UPDATE users SET name = LTRIM(name);
UPDATE users SET name = RTRIM(name);
UPDATE users SET len = LENGTH(name);
UPDATE users SET len = CHAR_LENGTH(name);
UPDATE users SET pos = POSITION('sub' IN name);
UPDATE users SET pos = LOCATE('sub', name);
UPDATE users SET pos = INSTR(name, 'sub');
UPDATE users SET name = LEFT(name, 5);
UPDATE users SET name = RIGHT(name, 5);
UPDATE users SET name = REPEAT('x', 10);
UPDATE users SET name = SPACE(10);
UPDATE users SET name = STRCMP(name1, name2);
UPDATE users SET name = FIELD(value, 'a', 'b', 'c');
UPDATE users SET name = ELT(position, 'a', 'b', 'c');
UPDATE users SET bits = BIT_COUNT(flags);
UPDATE users SET name = HEX(id);
UPDATE users SET name = UNHEX(hex_value);
UPDATE users SET name = INET_ATON(ip_address);
UPDATE users SET name = INET_NTOA(ip_number);
UPDATE users SET name = UUID();
UPDATE users SET name = VERSION();
UPDATE users SET name = DATABASE();
UPDATE users SET name = USER();
UPDATE users SET name = CURRENT_USER();
UPDATE users SET name = SESSION_USER();
UPDATE users SET name = SYSTEM_USER();
UPDATE users SET name = LAST_INSERT_ID();
UPDATE users SET name = CONNECTION_ID();
UPDATE users SET name = BENCHMARK(1000, expr);
UPDATE users SET name = CHARSET(name);
UPDATE users SET name = COLLATION(name);
UPDATE users SET name = WEIGHT_STRING(name);
UPDATE users SET geom = ST_GeomFromText('POINT(1 1)');
UPDATE users SET geom = ST_AsText(geom);
UPDATE users SET distance = ST_Distance(geom1, geom2);
UPDATE users SET name = "John" WHERE ST_Contains(geom, point);
UPDATE users SET name = "John" WHERE ST_Within(point, geom);
UPDATE users SET name = "John" WHERE ST_Intersects(geom1, geom2);
UPDATE `users` SET `name` = "John";
UPDATE `db`.`users` SET `name` = "John";
UPDATE users SET name = "John" WHERE `id` = 1;
UPDATE users AS u SET u.name = "John";
UPDATE users u SET u.name = "John";
UPDATE t1 AS a, t2 AS b SET a.col = b.col WHERE a.id = b.id;
UPDATE t1 a, t2 b SET a.col = b.col WHERE a.id = b.id;
