// Import pre-generated parsers from lib/parser/
// These are generated by running: gulp render && gulp generate
import { parse as athena } from '../lib/parser/athena'
import { parse as bigquery } from '../lib/parser/bigquery'
import { parse as db2 } from '../lib/parser/db2'
import { parse as flinksql } from '../lib/parser/flinksql'
import { parse as hive } from '../lib/parser/hive'
import { parse as mysql } from '../lib/parser/mysql'
import { parse as mariadb } from '../lib/parser/mariadb'
import { parse as noql } from '../lib/parser/noql'
import { parse as postgresql } from '../lib/parser/postgresql'
import { parse as redshift } from '../lib/parser/redshift'
import { parse as sqlite } from '../lib/parser/sqlite'
import { parse as transactsql } from '../lib/parser/transactsql'
import { parse as snowflake } from '../lib/parser/snowflake'
import { parse as trino } from '../lib/parser/trino'

export default {
  athena,
  bigquery,
  db2,
  flinksql,
  hive,
  mysql,
  mariadb,
  noql,
  postgresql,
  redshift,
  snowflake,
  sqlite,
  transactsql,
  trino,
}
